services:
  db:
    image: mongo:latest
    ports:
        - "27017:27017"
    container_name: w_books
  users:
    image: kabirsingh114/csc5991group1:users
    ports:
        - "5003:5000"
  books:
    image: kabirsingh114/csc5991group1:books
    ports:
        - "5004:5000"
  library:
    image: kabirsingh114/csc5991group1:library
    ports:
        - "5005:5000"
  recentlyadded:
    image: kabirsingh114/csc5991group1:recentlyAdded
    ports:
        - "5001:5000"
  rentals:
    image: kabirsingh114/csc5991group1:rentals
    ports:
        - "5006:5000"
  returns:
    image: kabirsingh114/csc5991group1:returns
    ports:
        - "5007:5000"
  trending:
    image: kabirsingh114/csc5991group1:trending
    ports:
        - "5002:5000"
  login:
    image: kabirsingh114/csc5991group1:login
    ports:
        - "8008:5000"
  ratings:
    image: kabirsingh114/csc5991group1:ratings
    ports:
      - "5009:5000"
  topten:
    image: kabirsingh114/csc5991group1:topten
    ports:
      - "5008:5000"
